#项目服务器配置

spring:
    datasource:
        druid:
            url: jdbc:mysql://127.0.0.1:3306/db_common?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
            username: root
            password: 123456
    redis:
        host: 127.0.0.1
        password:
        jedis:
          pool:
            min-idle: 0
            max-idle: 20
            max-active: 100





